// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/allanhechen/distributed-notification-system/utils/types"
	"github.com/google/uuid"
)

const createRequest = `-- name: CreateRequest :exec
INSERT INTO idempotent_requests(
    request_id,
    user_id,
    request_status_id,
    expires_at
) VALUES ($1, $2, $3, $4)
`

type CreateRequestParams struct {
	RequestID       uuid.UUID           `json:"request_id"`
	UserID          uuid.UUID           `json:"user_id"`
	RequestStatusID types.RequestStatus `json:"request_status_id"`
	ExpiresAt       time.Time           `json:"expires_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) error {
	_, err := q.db.Exec(ctx, createRequest,
		arg.RequestID,
		arg.UserID,
		arg.RequestStatusID,
		arg.ExpiresAt,
	)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT request_id, user_id, request_status_id, cached_response_code, cached_response, expires_at FROM idempotent_requests
WHERE request_id = $1
`

func (q *Queries) GetRequest(ctx context.Context, requestID uuid.UUID) (IdempotentRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, requestID)
	var i IdempotentRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.RequestStatusID,
		&i.CachedResponseCode,
		&i.CachedResponse,
		&i.ExpiresAt,
	)
	return i, err
}

const updateRequestFailed = `-- name: UpdateRequestFailed :execrows
UPDATE idempotent_requests SET
    request_status_id = 2
WHERE request_id = $1 AND request_status_id = 0 AND expires_at < NOW()
`

func (q *Queries) UpdateRequestFailed(ctx context.Context, requestID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequestFailed, requestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRequestReprocess = `-- name: UpdateRequestReprocess :execrows
UPDATE idempotent_requests SET
    request_status_id = 0,
    expires_at = $1
WHERE request_id = $2 AND
    (request_status_id = 2 OR
    (request_status_id = 0 AND expires_at < NOW()))
`

type UpdateRequestReprocessParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	RequestID uuid.UUID `json:"request_id"`
}

func (q *Queries) UpdateRequestReprocess(ctx context.Context, arg UpdateRequestReprocessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequestReprocess, arg.ExpiresAt, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRequestSuccess = `-- name: UpdateRequestSuccess :execrows
UPDATE idempotent_requests SET
    request_status_id = 1,
    expires_at = $1
WHERE request_id = $2 AND request_status_id = 0
`

type UpdateRequestSuccessParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	RequestID uuid.UUID `json:"request_id"`
}

func (q *Queries) UpdateRequestSuccess(ctx context.Context, arg UpdateRequestSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequestSuccess, arg.ExpiresAt, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
