// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRequest(ctx context.Context, arg CreateRequestParams) error
	GetRequest(ctx context.Context, requestID uuid.UUID) (IdempotentRequest, error)
	UpdateRequestFailed(ctx context.Context, requestID uuid.UUID) (int64, error)
	UpdateRequestReprocess(ctx context.Context, arg UpdateRequestReprocessParams) (int64, error)
	UpdateRequestSuccess(ctx context.Context, arg UpdateRequestSuccessParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
